# Talend CI/CD on Azure DevOps
# Build Pipeline for building and publishing on Talend Cloud   
trigger: none
pool:
 vmImage: 'AzurePipelineCI731'   
variables:
- group: Talend Configuration
- name: project_name
  value: 'containercicloud'
- name: job_name
  value: 'joindatadb'
- name: job_version
  value: '0.1'   
steps:
  - task: DownloadSecureFile@1
    name: settings_xml
    inputs:
      secureFile: settings.xml   
  - task: DownloadSecureFile@1
    name: license
    inputs:
      secureFile: license   
  - task: Maven@3
    inputs:
        mavenPomFile: '$(project_name)/poms/pom.xml' 
        mavenOptions:
          -Dlicense.path=$(license.secureFilePath)
          -Dtalend.studio.p2.base=$(p2_base)
          -Dtalend.studio.p2.update=$(p2_update)
          -Dpatch.path=$(patch.secureFilePath)
          -Dservice.url=$(talend_cloud_url)
          -Dcloud.token=$(talend_cloud_token)
          -Dcloud.publisher.screenshot=true
          -Xmx3096m -Xmx1024m
          -DaltDeploymentRepository=snapshots::default::http://localhost:8081/repository/snapshots/
        options: '--settings $(settings_xml.secureFilePath) -Pcloud-publisher - -pl $(jobs_to_build) -am -fae'
        goals: 'deploy'